version: '3.8'

networks:
  net_front:
  net_back:

volumes:
  db_storage:

services:
  web:
    image: nginx:1.25-alpine
    ports:
      - "4001:80"
    volumes:
      - ./src:/usr/share/nginx/html
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - net_front
      - net_back
    depends_on:
      - backend

  backend:
    image: php:8.3-fpm
    volumes:
      - ./src:/usr/share/nginx/html
    networks:
      - net_back

  database:
    image: mysql:8.3
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: superroot
      MYSQL_DATABASE: exampledb
      MYSQL_USER: dev
      MYSQL_PASSWORD: devpass
    volumes:
      - db_storage:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - net_back

  adminer:
    image: phpmyadmin:5.2
    ports:
      - "6001:80"
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: superroot
    networks:
      - net_back
      - net_front
